== Wildfly-Swarm addon for JBoss Forge
image:https://travis-ci.org/forge/wildfly-swarm-addon.svg?branch=master["Build Status", link="https://travis-ci.org/forge/wildfly-swarm-addon"]
image:http://img.shields.io/:license-EPL-blue.svg["License", link="https://www.eclipse.org/legal/epl-v10.html"]
image:https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/wildfly-swarm/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/wildfly-swarm"]

:idprefix: id_ 
This addon provides *standalone* functionality, and *exports services* for use in other addons. 

=== Installation

From Forge CLI:

[source,shell]
----
addon-install-from-git --url https://github.com/forge/wildfly-swarm-addon.git
----

=== Depends on
[options="header"]
|===
|Addon |Exported |Optional

|ui
|yes
|no

|projects
|yes
|no

|maven
|yes
|no
|===

== Features
Setup command:: 
Just type the following command if you're in shell. It should read Wildfly-Swarm: Setup if you're in a GUI environment:  
+
[source,java]
----
wildfly-swarm-setup
----
+
And that's it! The wildfly swarm maven plugin will be installed. 

Add Fraction::
You can install Wildfly Swarm Fractions by using the command `Wildfly-Swarm: Add Fraction`: 
+
[source,java]
----
[demo]$ wildfly-swarm-add-fraction --fractions 
batch-jberet         ejb                  jaxrs                jca                  keycloak             messaging            ribbon-secured       topology             undertow             
bean-validation      ejb-remote           jaxrs-cdi            jgroups              keycloak-server      monitor              security             topology-consul      webservices          
cdi                  hibernate-search     jaxrs-jaxb           jmx                  logging              msc                  spring               topology-jgroups     
connector            hibernate-validator  jaxrs-jsonp          jolokia              logstash             naming               spring-rest          topology-openshift   
datasources          infinispan           jaxrs-multipart      jpa                  mail                 remoting             swagger              topology-webapp      
ee                   io                   jaxrs-validator      jsf                  management           ribbon               swagger-webapp       transactions         

----
+
You can choose any fraction you want to install. Installed fractions are not listed.

Detect Fractions::
This will run a fraction analyzer algorithm and list the missing fractions. You can add them to your project by specifying the `--depend` parameter 

List Fractions::
This will list all the available fractions

WildFly Swarm Project type:: 
Allows creating a project with the Swarm maven plugin in place

Create Main Class:: 
Creates a Java Class with a main() method containing some basic code to boot Swarm and configure it in the swarm maven plugin.

Run:: 
Builds and executes the current swarmed project (in command line mode only so far) and will block the UI until Ctrl+C is pressed.
