== Wildfly-Swarm addon for JBoss Forge
image:https://travis-ci.org/forge/wildfly-swarm-addon.svg?branch=master["Build Status", link="https://travis-ci.org/forge/wildfly-swarm-addon"]

:idprefix: id_ 
This addon provides *standalone* functionality, and *exports services* for use in other addons. 

=== Installation

From Forge CLI:

[source,shell]
----
addon-install-from-git --url https://github.com/forge/wildfly-swarm-addon.git
----

=== Depends on
[options="header"]
|===
|Addon |Exported |Optional

|ui
|yes
|no

|projects
|yes
|no

|maven
|yes
|no
|===

== Setup

This Addon requires the following installation steps.

=== Add configuration to pom.xml 

To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
[source,xml]
----
<dependency>
   <groupId>org.jboss.forge.addon</groupId>
   <artifactId>wildfly-swarm-addon</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----
== Features
Wildfly-Swarm Setup command:: 
Just type the following command if you're in shell. It should read Wildfly-Swarm: Setup if you're in a GUI environment:  
+
[source,java]
----
wildfly-swarm-setup
----
+
And that's it! The wildfly swarm maven plugin will be installed. 

Wildfly-Swarm Add Fraction::
You can install Wildfly Swarm Fractions by using the command `Wildfly-Swarm: Add Fraction`: 
+
[source,java]
----
[demo]$ wildfly-swarm-add-fraction --fractions 
bean-validation      ee                   infinispan           jaxrs-weld           jolokia              mail                 remoting             topology             undertow             
connector            ejb-remote           jaxrs-jaxb           jca                  keycloak             messaging            ribbon               topology-jgroups     webservices          
container            hawkular             jaxrs-jsonp          jgroups              logging              msc                  ribbon-secured       topology-webapp      weld                 
datasources          hibernate-validator  jaxrs-multipart      jmx                  logstash             naming               security             transactions         

----
+
You can choose any fraction you want to install. Installed fractions are not listed.
